//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCURemittanceAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FormViewerEntities1 : DbContext
    {
        public FormViewerEntities1()
            : base("name=FormViewerEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CCURemittanceInvoiceInfo> CCURemittanceInvoiceInfoes { get; set; }
        public virtual DbSet<CCURemittanceHistory> CCURemittanceHistories { get; set; }
        public virtual DbSet<CCURemittanceMemberInfo> CCURemittanceMemberInfoes { get; set; }
    }
}
