//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCURemittanceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCURemittanceInvoiceInfo
    {
        public int ID { get; set; }
        public string InvoiceNum { get; set; }
        public string InvoiceDate { get; set; }
        public string VoucherNum { get; set; }
        public string VoucherDate { get; set; }
        public string WarNum { get; set; }
        public string WarDate { get; set; }
        public string FileName { get; set; }
    }
}
