//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCURemittanceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCURemittanceMemberInfo
    {
        public int ID { get; set; }
        public string Last { get; set; }
        public string First { get; set; }
        public string ClientID { get; set; }
        public string SSN { get; set; }
        public string ServiceDate { get; set; }
        public string BN { get; set; }
        public string SV { get; set; }
        public string Rate { get; set; }
        public string Units { get; set; }
        public string Gross { get; set; }
        public string Fee { get; set; }
        public string Net { get; set; }
        public string FileName { get; set; }
    }
}
